import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('zh'),
    Locale('ja'),
    Locale('ko'),
  ];

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(result != null, 'AppLocalizations not found in context');
    return result!;
  }

  String t(String key) {
    final code =
        supportedLocales.any((l) => l.languageCode == locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _localizedValues[code]?[key] ?? _localizedValues['en']![key] ?? key;
  }

  String tf(String key, Map<String, String> args) {
    var out = t(key);
    args.forEach((k, v) {
      out = out.replaceAll('{$k}', v);
    });
    return out;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'AIOC',
      'newChat': 'New Chat',
      'chat': 'Chat',
      'skills': 'Skills',
      'automations': 'Automations',
      'usage': 'Usage',
      'logout': 'Logout',
      'user': 'User',
      'language': 'Language',
      'languageEnglish': 'English',
      'languageChinese': '简体中文',
      'languageJapanese': '日本語',
      'languageKorean': '한국어',
      'generalAssistant': 'General Assistant',
      'startConversation': 'Start a conversation',
      'typeToStart': 'Type a message below to get started',
      'quickTasks': 'OpenClaw Quick Tasks',
      'systemInspect': 'System Inspect',
      'processSnapshot': 'Process Snapshot',
      'chartDemo': 'Chart Demo',
      'thinking': 'Thinking...',
      'copy': 'Copy',
      'copied': 'Copied to clipboard',
      'executionTimeline': 'Execution Timeline',
      'executionSummary': 'Execution Summary',
      'unknownComponent': 'Unknown Component: {component}',
      'selectDate': 'Select Date',
      'dataVisualization': 'Data Visualization',
      'invalidChartData': 'Invalid chart data',
      'typeOrAttach': 'Type a message or attach a file...',
      'fileReadError': 'Cannot read file content. Select a local text file.',
      'fileTooLarge': 'File too large (max {kb}KB).',
      'textFileOnly': 'Only text-like files are supported currently.',
      'fileEmpty': 'File content is empty.',
      'fileTruncated': 'File truncated to {chars} characters.',
      'filePickFailed': 'File selection failed: {error}',
      'fileAttachment': 'File Attachment',
      'signIn': 'Sign In',
      'email': 'Email',
      'password': 'Password',
      'serverConfiguration': 'Server Configuration',
      'serverUrl': 'Server URL',
      'serverUpdated': 'Server URL updated',
      'skillsSubtitle':
          'Skills over Models: choose capabilities, not model names.',
      'plan': 'Plan',
      'category': 'Category',
      'provider': 'Provider',
      'usageBilling': 'Usage & Billing',
      'failedLoadData': 'Failed to load data: {error}',
      'balance': 'Balance',
      'usageFor': 'Usage for {period}',
      'requests': 'Requests',
      'cost': 'Cost',
      'tokensIn': 'Tokens In',
      'tokensOut': 'Tokens Out',
      'features': 'Features',
      'streaming': 'Streaming',
      'tools': 'Tools',
      'models': 'Models',
      'maxSessions': 'Max Sessions',
      'createAutomation': 'Create Automation',
      'name': 'Name',
      'prompt': 'Prompt',
      'runEveryHours': 'Run every (hours)',
      'runImmediately': 'Run immediately',
      'cancel': 'Cancel',
      'create': 'Create',
      'createFailed': 'Create failed: {error}',
      'runFailed': 'Run failed: {error}',
      'runCompleted': 'Run completed | cost {cost} | request {request}',
      'loadRunsFailed': 'Failed to load runs: {error}',
      'automationRuns': 'Automation Runs',
      'noRunsYet': 'No runs yet',
      'status': 'Status',
      'started': 'Started',
      'inOut': 'in/out',
      'request': 'Request',
      'createScheduled':
          'Create scheduled workflows powered by selected skills.',
      'newAutomation': 'New automation',
      'noAutomationsYet': 'No automations yet',
      'everyHours': 'every {hours}h',
      'runNow': 'Run now',
      'runs': 'Runs',
      'pause': 'Pause',
      'resume': 'Resume',
      'delete': 'Delete',
    },
    'zh': {
      'appTitle': 'AIOC',
      'newChat': '新建对话',
      'chat': '聊天',
      'skills': '技能',
      'automations': '自动化',
      'usage': '用量',
      'logout': '退出登录',
      'user': '用户',
      'language': '语言',
      'languageEnglish': 'English',
      'languageChinese': '简体中文',
      'languageJapanese': '日本語',
      'languageKorean': '한국어',
      'generalAssistant': '通用助手',
      'startConversation': '开始对话',
      'typeToStart': '在下方输入消息开始使用',
      'quickTasks': 'OpenClaw 快速任务',
      'systemInspect': '系统巡检',
      'processSnapshot': '进程快照',
      'chartDemo': '图表演示',
      'thinking': '思考中...',
      'copy': '复制',
      'copied': '已复制到剪贴板',
      'executionTimeline': '执行时间线',
      'executionSummary': '执行摘要',
      'unknownComponent': '未知组件: {component}',
      'selectDate': '选择日期',
      'dataVisualization': '数据可视化',
      'invalidChartData': '图表数据无效',
      'typeOrAttach': '输入消息或添加文件...',
      'fileReadError': '无法读取文件内容，请选择本地文本文件。',
      'fileTooLarge': '文件过大（最大 {kb}KB）。',
      'textFileOnly': '当前仅支持文本类文件。',
      'fileEmpty': '文件内容为空。',
      'fileTruncated': '文件已截断为 {chars} 字符。',
      'filePickFailed': '选择文件失败: {error}',
      'fileAttachment': '文件附件',
      'signIn': '登录',
      'email': '邮箱',
      'password': '密码',
      'serverConfiguration': '服务器配置',
      'serverUrl': '服务器地址',
      'serverUpdated': '服务器地址已更新',
      'skillsSubtitle': 'Skills over Models：按能力选，不按模型名选。',
      'plan': '套餐',
      'category': '分类',
      'provider': '提供方',
      'usageBilling': '用量与计费',
      'failedLoadData': '加载数据失败: {error}',
      'balance': '余额',
      'usageFor': '{period} 用量',
      'requests': '请求数',
      'cost': '费用',
      'tokensIn': '输入 Tokens',
      'tokensOut': '输出 Tokens',
      'features': '功能',
      'streaming': '流式输出',
      'tools': '工具',
      'models': '模型',
      'maxSessions': '最大会话数',
      'createAutomation': '创建自动化',
      'name': '名称',
      'prompt': '提示词',
      'runEveryHours': '每隔（小时）运行',
      'runImmediately': '立即运行',
      'cancel': '取消',
      'create': '创建',
      'createFailed': '创建失败: {error}',
      'runFailed': '运行失败: {error}',
      'runCompleted': '运行完成 | 费用 {cost} | 请求 {request}',
      'loadRunsFailed': '加载运行记录失败: {error}',
      'automationRuns': '自动化运行记录',
      'noRunsYet': '暂无运行记录',
      'status': '状态',
      'started': '开始时间',
      'inOut': '输入/输出',
      'request': '请求',
      'createScheduled': '基于所选技能创建定时工作流。',
      'newAutomation': '新建自动化',
      'noAutomationsYet': '暂无自动化',
      'everyHours': '每 {hours} 小时',
      'runNow': '立即运行',
      'runs': '运行记录',
      'pause': '暂停',
      'resume': '恢复',
      'delete': '删除',
    },
    'ja': {
      'appTitle': 'AIOC',
      'newChat': '新規チャット',
      'chat': 'チャット',
      'skills': 'スキル',
      'automations': '自動化',
      'usage': '利用状況',
      'logout': 'ログアウト',
      'user': 'ユーザー',
      'language': '言語',
      'languageEnglish': 'English',
      'languageChinese': '简体中文',
      'languageJapanese': '日本語',
      'languageKorean': '한국어',
      'generalAssistant': '汎用アシスタント',
      'startConversation': '会話を開始',
      'typeToStart': '下にメッセージを入力して開始',
      'quickTasks': 'OpenClaw クイックタスク',
      'systemInspect': 'システム確認',
      'processSnapshot': 'プロセススナップショット',
      'chartDemo': 'チャートデモ',
      'thinking': '考え中...',
      'copy': 'コピー',
      'copied': 'クリップボードにコピーしました',
      'executionTimeline': '実行タイムライン',
      'executionSummary': '実行サマリー',
      'unknownComponent': '不明なコンポーネント: {component}',
      'selectDate': '日付を選択',
      'dataVisualization': 'データ可視化',
      'invalidChartData': 'チャートデータが無効です',
      'typeOrAttach': 'メッセージ入力またはファイル添付...',
      'fileReadError': 'ファイルを読み取れません。テキストファイルを選択してください。',
      'fileTooLarge': 'ファイルが大きすぎます（最大 {kb}KB）。',
      'textFileOnly': '現在はテキスト系ファイルのみ対応です。',
      'fileEmpty': 'ファイル内容が空です。',
      'fileTruncated': 'ファイルは {chars} 文字に切り詰められました。',
      'filePickFailed': 'ファイル選択に失敗: {error}',
      'fileAttachment': 'ファイル添付',
      'signIn': 'サインイン',
      'email': 'メール',
      'password': 'パスワード',
      'serverConfiguration': 'サーバー設定',
      'serverUrl': 'サーバーURL',
      'serverUpdated': 'サーバーURLを更新しました',
      'skillsSubtitle': 'Skills over Models: モデル名ではなく能力で選択。',
      'plan': 'プラン',
      'category': 'カテゴリ',
      'provider': 'プロバイダー',
      'usageBilling': '利用状況と課金',
      'failedLoadData': 'データ読み込み失敗: {error}',
      'balance': '残高',
      'usageFor': '{period} の利用状況',
      'requests': 'リクエスト',
      'cost': 'コスト',
      'tokensIn': '入力トークン',
      'tokensOut': '出力トークン',
      'features': '機能',
      'streaming': 'ストリーミング',
      'tools': 'ツール',
      'models': 'モデル',
      'maxSessions': '最大セッション',
      'createAutomation': '自動化を作成',
      'name': '名前',
      'prompt': 'プロンプト',
      'runEveryHours': '実行間隔（時間）',
      'runImmediately': '今すぐ実行',
      'cancel': 'キャンセル',
      'create': '作成',
      'createFailed': '作成失敗: {error}',
      'runFailed': '実行失敗: {error}',
      'runCompleted': '実行完了 | コスト {cost} | リクエスト {request}',
      'loadRunsFailed': '実行履歴の読み込み失敗: {error}',
      'automationRuns': '自動化実行履歴',
      'noRunsYet': '実行履歴はありません',
      'status': '状態',
      'started': '開始',
      'inOut': '入力/出力',
      'request': 'リクエスト',
      'createScheduled': '選択したスキルで定期ワークフローを作成。',
      'newAutomation': '新しい自動化',
      'noAutomationsYet': '自動化はまだありません',
      'everyHours': '{hours}時間ごと',
      'runNow': '今すぐ実行',
      'runs': '実行履歴',
      'pause': '一時停止',
      'resume': '再開',
      'delete': '削除',
    },
    'ko': {
      'appTitle': 'AIOC',
      'newChat': '새 채팅',
      'chat': '채팅',
      'skills': '스킬',
      'automations': '자동화',
      'usage': '사용량',
      'logout': '로그아웃',
      'user': '사용자',
      'language': '언어',
      'languageEnglish': 'English',
      'languageChinese': '简体中文',
      'languageJapanese': '日本語',
      'languageKorean': '한국어',
      'generalAssistant': '일반 어시스턴트',
      'startConversation': '대화 시작',
      'typeToStart': '아래에 메시지를 입력해 시작하세요',
      'quickTasks': 'OpenClaw 빠른 작업',
      'systemInspect': '시스템 점검',
      'processSnapshot': '프로세스 스냅샷',
      'chartDemo': '차트 데모',
      'thinking': '생각 중...',
      'copy': '복사',
      'copied': '클립보드에 복사됨',
      'executionTimeline': '실행 타임라인',
      'executionSummary': '실행 요약',
      'unknownComponent': '알 수 없는 컴포넌트: {component}',
      'selectDate': '날짜 선택',
      'dataVisualization': '데이터 시각화',
      'invalidChartData': '차트 데이터가 유효하지 않습니다',
      'typeOrAttach': '메시지를 입력하거나 파일을 첨부하세요...',
      'fileReadError': '파일 내용을 읽을 수 없습니다. 텍스트 파일을 선택하세요.',
      'fileTooLarge': '파일이 너무 큽니다 (최대 {kb}KB).',
      'textFileOnly': '현재 텍스트 파일만 지원합니다.',
      'fileEmpty': '파일 내용이 비어 있습니다.',
      'fileTruncated': '파일이 {chars}자로 잘렸습니다.',
      'filePickFailed': '파일 선택 실패: {error}',
      'fileAttachment': '파일 첨부',
      'signIn': '로그인',
      'email': '이메일',
      'password': '비밀번호',
      'serverConfiguration': '서버 설정',
      'serverUrl': '서버 URL',
      'serverUpdated': '서버 URL이 업데이트되었습니다',
      'skillsSubtitle': 'Skills over Models: 모델명이 아닌 기능 중심으로 선택하세요.',
      'plan': '플랜',
      'category': '카테고리',
      'provider': '제공자',
      'usageBilling': '사용량 및 요금',
      'failedLoadData': '데이터 로드 실패: {error}',
      'balance': '잔액',
      'usageFor': '{period} 사용량',
      'requests': '요청 수',
      'cost': '비용',
      'tokensIn': '입력 토큰',
      'tokensOut': '출력 토큰',
      'features': '기능',
      'streaming': '스트리밍',
      'tools': '도구',
      'models': '모델',
      'maxSessions': '최대 세션 수',
      'createAutomation': '자동화 생성',
      'name': '이름',
      'prompt': '프롬프트',
      'runEveryHours': '실행 주기(시간)',
      'runImmediately': '즉시 실행',
      'cancel': '취소',
      'create': '생성',
      'createFailed': '생성 실패: {error}',
      'runFailed': '실행 실패: {error}',
      'runCompleted': '실행 완료 | 비용 {cost} | 요청 {request}',
      'loadRunsFailed': '실행 기록 로드 실패: {error}',
      'automationRuns': '자동화 실행 기록',
      'noRunsYet': '실행 기록이 없습니다',
      'status': '상태',
      'started': '시작',
      'inOut': '입력/출력',
      'request': '요청',
      'createScheduled': '선택한 스킬 기반으로 예약 워크플로를 생성합니다.',
      'newAutomation': '새 자동화',
      'noAutomationsYet': '자동화가 없습니다',
      'everyHours': '{hours}시간마다',
      'runNow': '지금 실행',
      'runs': '실행 기록',
      'pause': '일시중지',
      'resume': '재개',
      'delete': '삭제',
    },
  };
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales.any(
      (l) => l.languageCode == locale.languageCode,
    );
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
